//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdRegistration
    {
        public StdRegistration()
        {
            this.SubjectAssigns = new HashSet<SubjectAssign>();
            this.StudentTeachers = new HashSet<StudentTeacher>();
        }
    
        public int Sid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> StudentCnic { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<SubjectAssign> SubjectAssigns { get; set; }
        public virtual ICollection<StudentTeacher> StudentTeachers { get; set; }
    }
}
