//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectAssign
    {
        public int SubAssignId { get; set; }
        public Nullable<int> SS_FK { get; set; }
        public Nullable<int> SR_FK { get; set; }
    
        public virtual StdRegistration StdRegistration { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
