//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherRegistration
    {
        public TeacherRegistration()
        {
            this.TeacherAssigns = new HashSet<TeacherAssign>();
            this.StudentTeachers = new HashSet<StudentTeacher>();
        }
    
        public int Tid { get; set; }
        public string TeacherName { get; set; }
        public Nullable<int> TeacherCnic { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> SubjectID { get; set; }
    
        public virtual ICollection<TeacherAssign> TeacherAssigns { get; set; }
        public virtual ICollection<StudentTeacher> StudentTeachers { get; set; }
    }
}
