//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherAssign
    {
        public int TSubAssignId { get; set; }
        public Nullable<int> TR_FK { get; set; }
        public Nullable<int> SS_FK { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual TeacherRegistration TeacherRegistration { get; set; }
    }
}
